### ISSUE TITLE
Leverage SQLite full text search

### ISSUE THREAD

**Issue by kevincianfarini** [JakeWharton/dodo#6]
I noticed that the search functionality uses `like` across the columns of interest. It might be worth it to investigate if [SQLite Full Text Search](https://www.sqlite.org/fts5.html) could be used to provide a more robust search experience (like tweets being ranked by relevance to the query).

I'd be more than happy to create a PR for this if you're open to it.

**Comment by JakeWharton** [comment]
Sure! It only doesn't because I was too lazy and was trying to finish in two days.

**Comment by kevincianfarini** [comment]
Awesome! I'll need to get myself set up and make a dummy twitter account. I currently dont have one. 

I have, however, been itching to play with FTS

**Comment by JakeWharton** [comment]
If you don't want to do that I can include some sample JSON responses which can be used to create a dummy database which is all that's needed to run the web UI.

**Comment by kevincianfarini** [comment]
That would be great. I try to avoid most social media, and I'd like to keep it that way.

**Comment by kevincianfarini** [comment]
I've got some time to play with this tonight if you're able to get some test data out there.

**Comment by JakeWharton** [comment]
[example.zip](https://github.com/JakeWharton/dodo/files/5543872/example.zip)

Zip file with example database containing some tweets.

You can build the app by running `./gradlew installDist` and then running it with `build/install/dodo/bin/dodo run --db example.db`. You'll have to pass the OAuth and API tokens as arguments as well, but you can just put in nonsense for them. As long as you don't hit the /sync endpoint they won't be used. The service runs at http://localhots:8098 locally.

**Comment by kevincianfarini** [comment]
Sorry for the delay. SQLite FTS requires that you insert records into the FTS virtual table (meaning for each tweet, we'll be inserting two records). This needs to be done at sync time, so the example database that's provided unfortunately won't work. 

I've applied for a twitter developer account and am awaiting a response.

**Comment by JakeWharton** [comment]
You could write a migration, since one will be required anyway to backfill all existing data in existing deployments.

**Comment by kevincianfarini** [comment]
You're totally right. Much better idea.
